/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#191c1e",
        "on-tertiary-fixed": "#351000",
        "on-tertiary-container": "#ffd2be",
        "surface-container-low": "#f2f4f6",
        "surface-container-high": "#e6e8ea",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#413f82",
        "surface-tint": "#4d44e3",
        "on-error-container": "#93000a",
        "surface-container": "#eceef0",
        "on-primary-container": "#dad7ff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#c3c0ff",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#e2dfff",
        "on-primary": "#ffffff",
        "tertiary-container": "#a44100",
        "on-primary-fixed": "#0f0069",
        "outline-variant": "#c7c4d8",
        "primary-container": "#4f46e5",
        "on-secondary-fixed": "#140f54",
        "on-error": "#ffffff",
        "primary": "#3525cd",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed-dim": "#c3c0ff",
        "surface-variant": "#e0e3e5",
        "error-container": "#ffdad6",
        "on-secondary-container": "#454386",
        "on-surface": "#191c1e",
        "on-surface-variant": "#464555",
        "secondary-container": "#b6b4ff",
        "tertiary": "#7e3000",
        "on-tertiary-fixed-variant": "#7b2f00",
        "surface": "#f7f9fb",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "secondary": "#58579b",
        "inverse-surface": "#2d3133",
        "primary-fixed": "#e2dfff",
        "surface-container-highest": "#e0e3e5",
        "outline": "#777587",
        "surface-dim": "#d8dadc",
        "on-primary-fixed-variant": "#3323cc",
        "inverse-primary": "#c3c0ff",
        "tertiary-fixed-dim": "#ffb695",
        "surface-bright": "#f7f9fb",
        "tertiary-fixed": "#ffdbcc",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
